-- -- Пропуски в обязательных полях
-- CREATE OR REPLACE VIEW v_dq_nulls AS
-- SELECT *
-- FROM f_contracts
-- WHERE supplier IS NULL OR buyer IS NULL
--    OR start_date IS NULL OR end_date IS NULL;

-- -- Плохие даты
-- CREATE OR REPLACE VIEW v_dq_bad_dates AS
-- SELECT *
-- FROM f_contracts
-- WHERE end_date < start_date;

-- -- Негативные суммы (не должно быть)
-- CREATE OR REPLACE VIEW v_dq_negative_value AS
-- SELECT *
-- FROM f_contracts
-- WHERE contract_value < 0;

-- -- Пересечения периодов по (buyer, supplier) — возможные дубли контрактов
-- CREATE OR REPLACE VIEW v_dq_overlaps AS
-- SELECT a.*
-- FROM f_contracts a
-- WHERE EXISTS (
--   SELECT 1
--   FROM f_contracts b
--   WHERE b.contract_id <> a.contract_id
--     AND b.buyer = a.buyer
--     AND b.supplier = a.supplier
--     AND daterange(b.start_date, b.end_date, '[]') &&
--         daterange(a.start_date, a.end_date, '[]')
-- );
