-- -- v_buyer_top_cpv: топ CPV по стране покупателя × год
-- CREATE OR REPLACE VIEW v_buyer_top_cpv AS
-- WITH agg AS (
--   SELECT
--     COALESCE(NULLIF(c.buyer_country,''), 'UNK') AS country,
--     EXTRACT(YEAR FROM c.award_date)::int        AS year,
--     LPAD(c.cpv_main::text, 8, '0')              AS cpv_code,   -- 8 знаков
--     COALESCE(d.name_en, LPAD(c.cpv_main::text,8,'0')) AS cpv_name,
--     COUNT(*)                                     AS awards,
--     SUM(c.contract_value)::numeric               AS spend_eur
--   FROM f_contracts c
--   LEFT JOIN cpv_dict d
--          ON LEFT(d.code, 8) = LPAD(c.cpv_main::text, 8, '0')  -- << ключевой фикс
--   WHERE c.award_date IS NOT NULL AND c.cpv_main IS NOT NULL
--   GROUP BY 1,2,3,4
-- )
-- SELECT
--   country, year, cpv_code, cpv_name, awards, spend_eur,
--   RANK() OVER (PARTITION BY country, year ORDER BY spend_eur DESC) AS rnk
-- FROM agg;

-- -- v_supplier_top_cpv: топ CPV по стране поставщика × год
-- CREATE OR REPLACE VIEW v_supplier_top_cpv AS
-- WITH agg AS (
--   SELECT
--     COALESCE(NULLIF(c.supplier_country,''), 'UNK') AS country,
--     EXTRACT(YEAR FROM c.award_date)::int           AS year,
--     LPAD(c.cpv_main::text, 8, '0')                 AS cpv_code,
--     COALESCE(d.name_en, LPAD(c.cpv_main::text,8,'0')) AS cpv_name,
--     COUNT(*)                                        AS awards,
--     SUM(c.contract_value)::numeric                  AS spend_eur
--   FROM f_contracts c
--   LEFT JOIN cpv_dict d
--          ON LEFT(d.code, 8) = LPAD(c.cpv_main::text, 8, '0')
--   WHERE c.award_date IS NOT NULL AND c.cpv_main IS NOT NULL
--   GROUP BY 1,2,3,4
-- )
-- SELECT
--   country, year, cpv_code, cpv_name, awards, spend_eur,
--   RANK() OVER (PARTITION BY country, year ORDER BY spend_eur DESC) AS rnk
-- FROM agg;
