-- -- C2C по стране × год (по стране покупателя; при желании сменить на supplier_country)
-- CREATE OR REPLACE VIEW v_c2c_country_year AS
-- SELECT
--   COALESCE(NULLIF(buyer_country,''), 'UNK') AS country,
--   EXTRACT(YEAR FROM COALESCE(award_date, start_date))::int AS year,
--   AVG(GREATEST(0,(end_date - start_date))/3.0)::numeric(10,2) AS dio_days,
--   AVG(GREATEST(0,payment_terms_d))::numeric(10,2)            AS dso_days,
--   AVG(30)::numeric(10,2)                                      AS dpo_days,  -- заглушка
--   COUNT(*)                                                    AS lines,
--   SUM(contract_value)::numeric(18,2)                          AS spend_eur
-- FROM f_contracts
-- GROUP BY 1,2;

-- -- Удобный срез для 2020 и 2023 (для сравнения на странице)
-- CREATE OR REPLACE VIEW v_c2c_country_2020_2023 AS
-- SELECT country, year, dio_days, dso_days, dpo_days,
--        (dio_days + dso_days - dpo_days) AS c2c_days,
--        lines, spend_eur
-- FROM v_c2c_country_year
-- WHERE year IN (2020, 2023);
